# Generated by Django 5.2.9 on 2026-03-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField(help_text='Write your HTML newsletter here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_sent', models.BooleanField(default=False, help_text='Tracks if this has been sent yet.')),
            ],
        ),
    ]
