# Generated by Django 5.2.9 on 2026-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Set display order, 0 is primary image'),
        ),
    ]
