# Generated by Django 5.2.9 on 2026-01-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0002_product_variant_image_product_variant_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product_variant',
            constraint=models.UniqueConstraint(fields=('product', 'image'), name='unique_variant_image_per_product'),
        ),
    ]
