# Generated by Django 5.2.9 on 2026-01-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0003_product_variant_unique_variant_image_per_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product_variant',
            name='unique_variant_image_per_product',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='image',
        ),
    ]
