# Generated by Django 5.2.9 on 2026-01-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0005_imagetag_taggedproduct_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sizes/'),
        ),
    ]
