# Generated by Django 5.2.9 on 2026-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0006_size_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='image',
        ),
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sizes/'),
        ),
    ]
