# Generated by Django 5.2.9 on 2026-01-13 18:01

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0007_remove_size_image_color_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedproduct',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedproduct',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='ImageTag',
        ),
        migrations.DeleteModel(
            name='TaggedProduct',
        ),
    ]
