# Generated by Django 5.2.9 on 2026-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0008_remove_taggedproduct_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='size',
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
