# Generated by Django 5.2.9 on 2026-02-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
