# Generated by Django 5.2.9 on 2026-03-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaFrayedApp', '0012_size_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
